### ISSUE TITLE
Counter – Grid System min-width: fit-content

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements-blocks#94]
``` scss
Code:
.flex-group > * {
   flex: 1;
    min-width: fit-content;
}
```

Also neu: Fügr in dein umgebenden Flex-Wrapper-Diver das min-width: fit-content; ein.

siehe dazu dieses Video:
https://www.youtube.com/watch?v=a0Tntm1RuWE&list=LL
